### ISSUE TITLE
[feature request] Search All Files

### ISSUE THREAD

**Issue by Westbrook** [divriots/webcomponents.dev#22]
I'd love to be able to search for a string in all files, much like `command + shift + f` allows for in VS Code. When I get into having a bunch of files open in a project it can sometimes be emblematic of my lack of organization that it is hard to remember which file I did what in, and having a search project interface would help solve that for me.

**Comment by gqio** [comment]
Hi,

Completely agree with the search feature cross files.
Do you expect a search like vs-code, are you happy with it ?

I mean what do you expect for a search feature like that ? Counting ? Listing files matching this filter ?
Do you expect also a replace All ?
Regex,strict, and full text search matching ?

Would love to hear what would be the best fit for your usage.

Thanks

**Comment by Westbrook** [comment]
I certainly use the full breadth of the search feature in VSCode, but my use context for webcomponent.dev is very different and greatly simplified. Primarily, when building "projects" with wc.dev, I'm looking to build a one of demo, or presentation that I'm not likely to manage long term. In that way, I may be a bit helter-skelter and need to find something, but _I_ am not likely to need some of the more advanced refactoring tools you see in the search UI for VSCode. That's not to say I wouldn't use them if that popped up in my editor one day, just that I don't feel like they would have a large effect of my usage of the product.

**Comment by gqio** [comment]
Ok I see, thx for sharing.
I have some ideas now :D
Will see what it's coming from them.

Stay tuned.

**Comment by gqio** [comment]
Good news.

We implemented a quick search accross all files, in the online editor.

cmd + shift + F

![image](https://user-images.githubusercontent.com/1063530/124153715-042d6c00-da95-11eb-8b8d-f058ef85c44a.png)

also cmd + P will give you a quick switch on files

![image](https://user-images.githubusercontent.com/1063530/124153850-2fb05680-da95-11eb-9d16-b1a6748e0aac.png)


Hope you find it useful.

Thanks
