### ISSUE TITLE
Preview shows "last completed" rather than "last saved" build.

### ISSUE THREAD

**Issue by Westbrook** [divriots/webcomponents.dev#23]
**Describe the bug**

If I save my component too many times in short order then I can get into a state where the preview will display the "last completed" but not "last saved" build of my code, which can be confusing (especially while debugging).

**To Reproduce**
Reproduction of this is difficult, and may be a function of project scale, but when working on https://webcomponents.dev/edit/5sXaRWYCLldZnVq9VjzT I would often fine that this occurred when habitually saving lines/parts of a change, as opposed to the complete change.

**Expected behavior**
The preview UI should alway display the "last started" build, no matter of completion order.

**Device**
 - OS: MacOS
 - Browser: Chrome and Edge
 - Version: Latest

**Comment by gqio** [comment]
@Westbrook do you still experience this issue ? I close it but feel free to reopen it or raise a new issue.

Thanks
