### ISSUE TITLE
Manage file structure under src

### ISSUE THREAD

**Issue by DevOpsDave** [divriots/webcomponents.dev#51]
It would be good if there was a way to create new directories under src.  Not seeing how to do that.

**Comment by gqio** [comment]
Hi @DevOpsDave 

Webcomponents.dev is meant to be used for single component. So we tried to propose a simple structure to show your component and separating concern of tests/stories/demo/code.

If you need a more complicated file structure or multi components oriented we have also a product [backlight.dev](https://backlight.dev) 
Please come and join us on [discord](https://discord.com/channels/744781525119139859/744783031125934121) if you need any help or assistance on webcomponents.dev

we also have a channel dedicated to backlight.dev (still in early acces)

Thanks
