### ISSUE TITLE
cannot connect to github or git lab

### ISSUE THREAD

**Issue by tongshen9095** [divriots/webcomponents.dev#55]
**Describe the bug**

**To Reproduce**

click create and then ok, shows repostory setup failed
for gitlab, login then see bad gateway

**Expected behavior**

**Screenshots**

**Device**
 - OS: 
 - Browser: chrome or safari
 - Version: 

**Additional context**

**Comment by gqio** [comment]
Hi @tongshen9095 

I tested this morning, it works

We will revamp this feature to make it one click.

Please reopen this issue if you encounter again any errors.
I will be available on [Discord](https://discord.gg/z7JUzhn) if you need any help.

Thanks
