### ISSUE TITLE
WCD Crashes by Dev Tools

### ISSUE THREAD

**Issue by jorenbroekema** [divriots/webcomponents.dev#62]
### 📖 Reproduction steps

1. Use latest stable chrome 92.0.4515.159
2. Use Incognito mode (or normal mode works as well)
3. Go to https://webcomponents.dev/edit/LWuupe7NoXwlpP9BiJoG/src/index.stories.js?branch=release@us8AQfqqmBQfx9Q4gGb16drlYbL2 or run WCD locally (yarn wcd:watch)
4. Go into edit mode
5. Open Dev Tools, start messing around in the Elements inspector, click some divs, it should crash within a minute of doing that, at least for me it is very consistent within 10 seconds or so.

### 🙁 Current Behavior

Dev Tools crashing WCD. Or WCD crashing DevTools, not sure, but the browser crashes.

### 🙂 Expected Behavior

The browser not to crash :)

### 🌐 What browser(s) are you seeing the problem on?

Chrome

### Browser version(s)

92.0.4515.159

**Comment by gqio** [comment]
Fixed with latest version, please reopen if you encounter any issue.
